# -*- mode: python ; coding: utf-8 -*-

import sys
import os
from pathlib import Path

# Получаем путь к PyQt6
import PyQt6
pyqt6_dir = os.path.dirname(PyQt6.__file__)

# Ищем плагины PyQt6
qt_plugins_dir = os.path.join(pyqt6_dir, 'Qt6', 'plugins')

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        # Иконка приложения
        ('app_icon.ico', '.'),
        ('app_icon.png', '.'),
    ],
    hiddenimports=[
        # Админ панель
        'admin',
        'admin.auth_dialog',
        'admin.notifications_dialog',
        'admin.styles',
        'admin.admin_panel',
        'admin.admin_panel.main_window',
        'admin.admin_panel.tabs.computers_tab',
        'admin.admin_panel.tabs.groups_tab',
        'admin.admin_panel.tabs.users_tab',
        'admin.admin_panel.tabs.reports_tab',
        'admin.admin_panel.dialogs.computer_dialogs',
        'admin.admin_panel.dialogs.user_dialogs',
        'admin.computer_details',
        'admin.computer_details.main_window',
        'admin.computer_details.overview_tab',
        'admin.computer_details.metrics_tab',
        'admin.computer_details.events_tab',
        'admin.computer_details.sessions_tab',
        'admin.computer_details.anomalies_tab',
        'admin.computer_details.reports_tab',
        'admin.computer_details.ai_analysis_tab',
        'admin.computer_details.widgets',
        'admin.computer_details.dialogs',
        # Агент
        'agent',
        'agent.remote_agent',
        'agent.settings_dialog',
        'agent.styles',
        'agent.diagnostics',
        'agent.diagnostics.events',
        'agent.diagnostics.recovery',
        'agent.diagnostics.logger',
        'agent.diagnostics.heartbeat',
        'agent.diagnostics.ack',
        'agent.diagnostics.watchdog',
        'agent.diagnostics.state_machine',
        # Коллекторы
        'collectors',
        'collectors.metrics_collector',
        'collectors.windows_events',
        'collectors.applications_collector',
        'collectors.event_grouper',
        # Ядро
        'core',
        'core.api_client',
        'core.hardware_id',
        'core.system_monitor',
        # Хранилище
        'storage',
        'storage.json_logger',
        'storage.cloud_uploader',
        # Утилиты
        'utils',
        'utils.constants',
        'utils.dependencies',
        'utils.platform_utils',
        # Скрытые импорты qtpy
        'qtpy',
        'qtpy.QtWidgets',
        'qtpy.QtCore',
        'qtpy.QtGui',
        'qtpy.QtNetwork',
        'qtpy.QtSvg',
        'qtpy.QtWebSockets',
        'qtpy.QtMultimedia',
        'qtpy.QtWebEngineWidgets',
        # Для работы с PyQt6
        'PyQt6',
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'PyQt6.QtWidgets',
        'PyQt6.QtNetwork',
        'PyQt6.QtSvg',
        'PyQt6.QtWebSockets',
        'PyQt6.QtMultimedia',
        # Зависимости
        'pymysql',
        'psutil',
        'pyautogui',
        'mss',
        'PIL',
        'PIL.Image',
        'PIL.ImageGrab',
        'websockets',
        'pynput',
        'pynput.keyboard',
        'pynput.mouse',
        'boto3',
        'boto3.session',
        'requests',
        # Windows-specific
        'ctypes',
        'ctypes.wintypes',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Исключаем PyQt5 полностью
        'PyQt5',
        'PyQt5.QtCore',
        'PyQt5.QtGui',
        'PyQt5.QtWidgets',
        'PyQt5.QtNetwork',
        'PyQt5.QtSvg',
        'PyQt5.QtWebSockets',
        'PyQt5.QtMultimedia',
        'PyQt5.QtWebEngineWidgets',
        'PyQt5.QtWebEngineCore',
        'PyQt5.QtPrintSupport',
        'PyQt5.QtQml',
        'PyQt5.QtQuick',
        'PyQt5.QtQuickWidgets',
        'PyQt5.QtSql',
        'PyQt5.QtTest',
        'PyQt5.QtXml',
        'PyQt5.QtDBus',
        'PyQt5.QtDesigner',
        'PyQt5.QtHelp',
        'PyQt5.QtOpenGL',
        'PyQt5.QtPositioning',
        'PyQt5.QtSerialPort',
        'PyQt5.QtX11Extras',
        'PyQt5.uic',
        '_PyQt5',
        # Исключаем ненужные модули
        'tkinter',
        'matplotlib',
        'scipy',
        'sympy',
        'pandas',
        'numpy',
        'notebook',
        'IPython',
        'jupyter',
        'zmq',
        'setuptools',
        'pip',
        'curses',
        'lib2to3',
        'distutils',
        'venv',
        'ensurepip',
        'unittest',
        'pydoc',
        'test',
        'http.server',
        'xmlrpc',
        'socketserver',
        'email.mime',
        'email.mime.multipart',
        'nntplib',
        'poplib',
        'smtpd',
        'telnetlib',
        'webbrowser',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

# Добавляем плагины PyQt6
a.datas += Tree(qt_plugins_dir, prefix='PyQt6/Qt6/plugins')

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='PC-RMDS-Host',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,          # Без консоли
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='app_icon.ico',
)